image:
  repository: big-hitter-api
  tag: 0.2.0

service:
  port: 3006
  targetPort: 3006

ingress:
  enabled: true
  hosts:
    - host: big-hitter-api.local
      paths:
        - path: /
          pathType: ImplementationSpecific

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
